"""empty message

Revision ID: 059487afa708
Revises: e2f3b3da514e
Create Date: 2021-02-01 15:37:27.988746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059487afa708'
down_revision = 'e2f3b3da514e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
