"""empty message

Revision ID: e2f3b3da514e
Revises: 
Create Date: 2021-01-26 15:20:53.369982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f3b3da514e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc', sa.Column('file', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc', 'file')
    # ### end Alembic commands ###
