"""Initial migration.

Revision ID: 44ac0b391eef
Revises: d3b95a31ca8a
Create Date: 2021-04-15 18:36:02.430456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ac0b391eef'
down_revision = 'd3b95a31ca8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('facebook', sa.String(length=80), nullable=True))
    op.add_column('userinfo', sa.Column('instagram', sa.String(length=80), nullable=True))
    op.add_column('userinfo', sa.Column('telegram', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userinfo', 'telegram')
    op.drop_column('userinfo', 'instagram')
    op.drop_column('userinfo', 'facebook')
    # ### end Alembic commands ###
