"""Initial migration.

Revision ID: 617455de17f2
Revises: 
Create Date: 2021-02-15 17:00:37.416290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617455de17f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=9), nullable=True),
    sa.Column('phone_verification', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('email_verification', sa.Boolean(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinfo')
    # ### end Alembic commands ###
