"""comment model update

Revision ID: 88c5b49a9e52
Revises: 44ac0b391eef
Create Date: 2021-05-14 08:44:17.128857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c5b49a9e52'
down_revision = '44ac0b391eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('childs', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'comment', ['childs'], ['parent_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'childs')
    # ### end Alembic commands ###
