"""Initial migration.

Revision ID: d3b95a31ca8a
Revises: 617455de17f2
Create Date: 2021-04-15 18:31:47.427476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b95a31ca8a'
down_revision = '617455de17f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('position', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userinfo', 'position')
    # ### end Alembic commands ###
